version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=dsqdaf8zBF5w/doewo@
      - MYSQL_DATABASE=myschool
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/myschool
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "dsqdaf8zBF5w/doewo@"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone



